### ISSUE TITLE
Please post .hex file for MIVA 1 U

### ISSUE THREAD

**Issue by cathmart** [maasijam/eurorack#1]
I have tried to compile the code for the MIVA 1 U, I just cant, will you please just put up the hex file.

**Comment by maasijam** [comment]
Hi,
did you install the OneButton library? https://github.com/mathertel/OneButton
Anyway I've just uploaded the hex file. https://github.com/maasijam/eurorack/tree/master/1u/miva/software
Best regards
Tom

**Comment by cathmart** [comment]
Thank you so much.

**Comment by cathmart** [comment]
I have completed the upload of the hex, easy, thank you again. When I get over the trauma of my trying to use the Arduino IDE to compile, I will go back and use the one button library to learn how to do it myself. I did update a number of library's while trying to complete this but the information I could find got less and less. The module is fantastic, thank you for providing it. I had to get 5 sets made, I will give the ones I am not using away to my local (Australia) modular community for free.
