### ISSUE TITLE
OSGO Nano header sockets, etc

### ISSUE THREAD

**Issue by tripslip38** [maasijam/eurorack#4]
Trying to piece together a component order and looking for stuff that might not be on the BOM. 

1. Studying your side profile photos of the Arduino Nano stacked onto the PCB it looks like sockets that are partially engaged? Are you able to elaborate a little more on that?  
2. The 2x8 at the bottom of the board...I guess that's the larger ribbon connector to support both 12V eurorack power and 5V for the Nano? Do you know what is the standard component for that? Is [this](https://www.digikey.com/en/products/detail/adam-tech/BHR-16-VUA/9832329?utm_adgroup=General&utm_source=google&utm_medium=cpc&utm_campaign=PMax%20Shopping_Product_Zombie%20SKUs&utm_term=&utm_content=General&utm_id=go_cmp-17815035045_adg-_ad-__dev-c_ext-_prd-9832329_sig-CjwKCAiA4smsBhAEEiwAO6DEjSk8p2BpCr-RZCxoS-sNCqpDWoAA7F_pEGc0A93pzyJDpshrMpAeRBoCMZ0QAvD_BwE&gad_source=1&gclid=CjwKCAiA4smsBhAEEiwAO6DEjSk8p2BpCr-RZCxoS-sNCqpDWoAA7F_pEGc0A93pzyJDpshrMpAeRBoCMZ0QAvD_BwE) the correct pin pitch? 
3. Threaded standoffs: Do you have a spec?
Thank you very much!

**Comment by maasijam** [comment]
Hi,
I've updated the BOM. Hopefully that makes it a little more understandable,

1. The Arduino is plugged into a 2*14 IC socket (pin 15/16 of the Arduino are not needed)
2. Yes, the 5V comes from the eurorack power. The header in your link is correct.
3. See the updated BOM

Best regards

**Comment by tripslip38** [comment]
> Hi, I've updated the BOM. Hopefully that makes it a little more understandable,
> 
> 1. The Arduino is plugged into a 2*14 IC socket (pin 15/16 of the Arduino are not needed)
> 2. Yes, the 5V comes from the eurorack power. The header in your link is correct.
> 3. See the updated BOM
> 
> Best regards

Thank you, Maasijam!
